name: Deno

on:
    push:
        branches: ['main', 'feature_game']
    pull_request:
        branches: ['main']

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Verify formatting
              run: deno fmt --check

            - name: Run linter
              run: deno lint --rules-exclude=no-this-alias,no-unused-vars

            - name: Run tests
              run: deno test -A
